apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: selfsigned-ca-certificate
spec:
  secretName: jitsi-tls-ca-key-pair
  dnsNames:
  - "*.jitsi.faults.quest"
  isCA: true
  issuerRef:
    name: selfsigned-cluster-issuer
    kind: ClusterIssuer
