apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: selfsigned-certificate
spec:
  secretName: jitsi-key-pair
  dnsNames:
  - "*.jitsi.faults.quest"
  isCA: false
  issuerRef:
    name: selfsigned-issuer
    kind: Issuer

